import { customFetch } from "../../libs/orval";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import type { SignInRequest, SignUpRequest } from "../api.schemas";

export type usersSignInResponse = {
  data: void | void;
  status: number;
  headers: Headers;
};

export const getUsersSignInUrl = () => {
  return `/users/sign-in`;
};

export const usersSignIn = async (
  signInRequest: SignInRequest,
  options?: RequestInit,
): Promise<usersSignInResponse> => {
  return customFetch<usersSignInResponse>(getUsersSignInUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signInRequest),
  });
};

export type usersSignUpResponse = {
  data: void | void;
  status: number;
  headers: Headers;
};

export const getUsersSignUpUrl = () => {
  return `/users/sign-up`;
};

export const usersSignUp = async (
  signUpRequest: SignUpRequest,
  options?: RequestInit,
): Promise<usersSignUpResponse> => {
  return customFetch<usersSignUpResponse>(getUsersSignUpUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(signUpRequest),
  });
};
