version: '3.9'

services:
  db:
    image: postgres:17.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  db-store: