/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import { Hono } from "hono";
import { tasksListTasksHandlers } from "../handlers/tasksListTasks";

const app = new Hono();

app.get("/tasks", ...tasksListTasksHandlers);

export default app;
