/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import type { Context, Env } from "hono";

import type { TasksListTasksParams } from "./models";

export type TasksListTasksContext<E extends Env = any> = Context<
  E,
  "/tasks",
  { in: { query: TasksListTasksParams }; out: { query: TasksListTasksParams } }
>;
