/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from "zod";

export const tasksListTasksQueryParams = zod.object({
  limit: zod.number(),
  offset: zod.number(),
});

export const tasksListTasksResponseTasksItemTitleMax = 100;

export const tasksListTasksResponse = zod.object({
  tasks: zod.array(
    zod.object({
      id: zod.string(),
      title: zod.string().min(1).max(tasksListTasksResponseTasksItemTitleMax),
      status: zod.enum(["todo", "inProgress", "done"]),
    }),
  ),
  total: zod.number(),
});
