import { customFetch } from "../../libs/orval";
/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import type { TasksListTasks200, TasksListTasksParams } from "../api.schemas";

export type tasksListTasksResponse = {
  data: TasksListTasks200;
  status: number;
  headers: Headers;
};

export const getTasksListTasksUrl = (params: TasksListTasksParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  return normalizedParams.size
    ? `/tasks?${normalizedParams.toString()}`
    : `/tasks`;
};

export const tasksListTasks = async (
  params: TasksListTasksParams,
  options?: RequestInit,
): Promise<tasksListTasksResponse> => {
  return customFetch<tasksListTasksResponse>(getTasksListTasksUrl(params), {
    ...options,
    method: "GET",
  });
};
