/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */

export interface SignInRequest {
  /**
   * メールアドレス
   * @minLength 1
   */
  email: string;
  /**
   * パスワード
   * @minLength 1
   */
  password: string;
}
