/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import type { TaskStatus } from "./taskStatus";

export interface Task {
  /** タスクID */
  id: string;
  /**
   * タスク名
   * @minLength 1
   * @maxLength 100
   */
  title: string;
  /** 進行状態 */
  status: TaskStatus;
}
