/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */

export type TasksListTasksParams = {
  /**
   * 取得上限件数
   */
  limit: number;
  /**
   * 取得開始位置
   */
  offset: number;
};
