/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import type { Task } from "./task";

export type TasksListTasks200 = {
  tasks: Task[];
  total: number;
};
