/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from "zod";

export const usersSignInBody = zod.object({
  email: zod.string().min(1),
  password: zod.string().min(1),
});

export const usersSignUpBodyPasswordMin = 8;

export const usersSignUpBody = zod.object({
  email: zod.string().min(1),
  password: zod.string().min(usersSignUpBodyPasswordMin),
});
