/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 0.0.0
 */
import type { Context, Env } from "hono";

import { SignInRequest, SignUpRequest } from ".././models";

export type UsersGetSelfContext<E extends Env = any> = Context<
  E,
  "/users/self"
>;
export type UsersSignInContext<E extends Env = any> = Context<
  E,
  "/users/sign-in",
  { in: { json: SignInRequest }; out: { json: SignInRequest } }
>;
export type UsersSignOutContext<E extends Env = any> = Context<
  E,
  "/users/sign-out"
>;
export type UsersSignUpContext<E extends Env = any> = Context<
  E,
  "/users/sign-up",
  { in: { json: SignUpRequest }; out: { json: SignUpRequest } }
>;
